# Generated by Django 4.2.8 on 2025-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_verified_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
