# Generated by Django 4.2.8 on 2025-05-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('external_meeting_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribed', 'Transcribed'), ('summarized', 'Summarized')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('external_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('join_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meetings.meeting')),
            ],
        ),
    ]
