# Generated by Django 4.2.8 on 2025-05-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='zoom_profile',
        ),
    ]
