# Generated by Django 4.2.8 on 2025-05-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_meeting_zoom_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
