# Generated by Django 4.2.8 on 2025-05-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_join_url_meeting_start_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='join_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
