# Generated by Django 4.2.8 on 2025-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meeting_join_url_alter_meeting_start_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
