# Generated by Django 4.2.8 on 2025-06-04 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting'),
        ),
    ]
