# Generated by Django 4.2.8 on 2025-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='cohere_insights',
            field=models.JSONField(blank=True, help_text='Insights or output from Cohere AI', null=True),
        ),
    ]
