# Generated by Django 4.2.8 on 2025-06-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_transcript_cohere_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='utterances',
            field=models.JSONField(blank=True, help_text='List of utterance blocks with speaker, time, text', null=True),
        ),
    ]
