# Generated by Django 4.2.8 on 2025-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_transcript_utterances'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='speakers_updated',
            field=models.BooleanField(default=False),
        ),
    ]
