# Generated by Django 4.2.8 on 2025-06-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0005_transcript_speakers_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='speaker_map',
            field=models.JSONField(blank=True, help_text='Mapping of speaker codes to human names', null=True),
        ),
    ]
