# Generated by Django 4.2.8 on 2025-05-30 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_org_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_profile', to='integrations.oauthtoken')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_profiles', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organisation', 'zoom_user_id')},
            },
        ),
    ]
