# Generated by Django 4.2.8 on 2025-06-04 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomprofile',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_profiles', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to='organisations.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthtoken',
            unique_together={('organisation', 'provider')},
        ),
    ]
