# Generated by Django 4.2.8 on 2025-05-30 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_zoomprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoomprofile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='oauthtoken',
            unique_together={('user', 'provider')},
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='zoomprofile',
            name='organisation',
        ),
    ]
