# Generated by Django 4.2.8 on 2025-05-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_zoomprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoomprofile',
            old_name='email',
            new_name='zoom_email',
        ),
    ]
