# Generated by Django 4.2.8 on 2025-05-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_rename_email_zoomprofile_zoom_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomprofile',
            name='zoom_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
