# Generated by Django 4.2.8 on 2025-05-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(default='ABCDEFGH', editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
